### ISSUE TITLE
[Feature Request] Add ifn't and whilen't tokens 

### ISSUE THREAD

**Issue by PrashantGyawali** [pes18fan/zen#3]
The language is good and simple with "if else" but it can be better with ifn't and whilen't syntax

Use case: ifn't and whilen't will prevent the need to use the not operator in the code  

![image](https://github.com/pes18fan/zen/assets/49340437/8b298a2b-f296-490b-ac8d-f027bdc8e731)

**Comment by pes18fan** [comment]
That sounds absolutely crazy. I'll do it.

**Comment by pes18fan** [comment]
Lexing the apostrophes in the middle is a rather tough task. What about `ifnot` and `whilenot`?

Although perhaps those aren't as funny.

**Comment by pes18fan** [comment]
Or perhaps just `ifnt` and `whilent` without the apostrophes?

**Comment by pes18fan** [comment]
Nevermind, I might have figured out a way.

**Comment by pes18fan** [comment]
It's done. Was easier than I thought. PR soon.

*(why the hell am I doing this)*
